In [2]:
# Defining project paths
BASE_DIR = "D:/Capstone/capstone_repo"
DATA_DIR = f"{BASE_DIR}/data"
NB_DIR = f"{BASE_DIR}/notebooks"

import os
os.makedirs(DATA_DIR, exist_ok=True)

In [3]:
import osmnx as ox
import networkx as nx
import geopandas as gpd
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [32]:
def wrangle(df):
    df_clean = df[["name", 'lat', 'lon']].copy()
    df_clean = df_clean.drop_duplicates()
    df_clean = df_clean.dropna(subset=['lat', 'lon'])
    
    return df_clean

In [33]:
def save_clean_data(df, filename):
    filepath = os.path.join(f"{DATA_DIR}/processed", filename)
    df.to_csv(filepath, index=False)

# Hospitals data

In [34]:
hospitals = pd.read_csv(f"{DATA_DIR}/raw/casablanca_healthcare.csv")
hospitals.head()

,name,amenity,geometry,lat,lon
0,Clinique Badr مصحة بدر,clinic,POINT (-7.6410981 33.5948697),33.594870,-7.641098
1,clinique dentaire casablanca (cdc),clinic,POINT (-7.6482094 33.5874104),33.587410,-7.648209
2,Centre consultation et traitement dentaires,hospital,POINT (-7.6206013 33.5730773),33.573077,-7.620601
3,Clinique d'accouchement,clinic,POINT (-7.6240936 33.5930596),33.593060,-7.624094
4,Hôpital Sidi Othmane,hospital,POINT (-7.5733008 33.5585424),33.558542,-7.573301

In [35]:
healthcare_cleaned = wrangle(hospitals)
healthcare_cleaned.shape

(105, 3)

In [36]:
save_clean_data(healthcare_cleaned, "casablanca_healthcare_cleaned.csv")

# Public Transport data

In [37]:
transport_stops = pd.read_csv(f"{DATA_DIR}/raw/casablanca_transport_stops.csv")
transport_stops.head()

,name,public_transport,geometry,lat,lon
0,Marjane Drissia M6,platform,POINT (-7.5946468 33.5618694),33.561869,-7.594647
1,Usine de Thé,platform,POINT (-7.5161146 33.6013266),33.601327,-7.516115
2,Sakani,platform,POINT (-7.4821131 33.6036527),33.603653,-7.482113
3,Résidence El Hamd,platform,POINT (-7.5424947 33.5573105),33.557310,-7.542495
4,Groupe Scolaire La Fourmilière,platform,POINT (-7.665272 33.5805828),33.580583,-7.665272

In [38]:
transport_stops["public_transport"].value_counts()

public_transport
platform         1616
stop_position     177
Name: count, dtype: int64

In [39]:
transport_stops_cleaned = wrangle(transport_stops)
transport_stops_cleaned.shape

(1793, 3)

In [40]:
save_clean_data(transport_stops_cleaned, "casablanca_transport_stops_cleaned.csv")